name: Spell Check (codespell - CLI)

on:
  push:
  pull_request:

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install "codespell>=2,<3"
      - name: Run codespell (reads .codespellrc)
        run: codespell --config .codespellrc .
